---
# Demo playbook

- name: Removing Tenant
  hosts: apic
  vars_files:
    - vars.yml
  gather_facts: no
  vars:
    aci_login: &aci_login
      hostname: '{{ aci_hostname }}'
      username: '{{ aci_username }}'
      password: '{{ aci_password }}'
      validate_certs: no

  tasks:
  - name: Remove Tenant
    aci_tenant:
      <<: *aci_login
      tenant: '{{ tenant }}'
      description: 'tenant'
      state: absent
    delegate_to: localhost

  - name: Remove VRF
    aci_vrf:
      <<: *aci_login
      tenant: '{{ tenant }}'
      vrf_name: '{{ vrf }}'
      state: absent
    delegate_to: localhost

  - name: Removing BD
    aci_bd:
      <<: *aci_login
      tenant: '{{ tenant }}'
      vrf: '{{ vrf }}'
      bd: '{{ bd.name }}'
      state: absent
    delegate_to: localhost

  - name: Remove Removing Subnet
    aci_bd_subnet:
      <<: *aci_login
      tenant: '{{ tenant }}'
      bd: '{{ bd.name }}'
      gateway: '{{ bd.ip }}'
      mask: '{{ bd.mask }}'
      state: absent
    delegate_to: localhost

  - name: Remove AP
    aci_ap:
      <<: *aci_login
      tenant: '{{ tenant }}'
      app_profile: '{{ app_profile }}'
      state: absent
    delegate_to: localhost

  - name: Remove web_epg
    aci_epg:
      <<: *aci_login
      tenant: '{{ tenant }}'
      app_profile: '{{ app_profile }}'
      epg: '{{ epg1 }}'
      state: absent
    delegate_to: localhost

  - name: Remove db_epg
    aci_epg:
      <<: *aci_login
      tenant: '{{ tenant }}'
      app_profile: '{{ app_profile }}'
      epg: '{{ epg2 }}'
      state: absent
    delegate_to: localhost

  - name: Remove Filter
    aci_filter:
      <<: *aci_login
      tenant: '{{ tenant }}'
      filter: '{{ filter }}'
      state: absent
    delegate_to: localhost

  - name: Remove Filter Entry
    aci_filter_entry:
      <<: *aci_login
      tenant: '{{ tenant }}'
      filter: '{{ filter }}'
      filter_entry: '{{ filter_entry }}'
      state: absent
    delegate_to: localhost

  - name: Remove Tenant Contract
    aci_contract:
      <<: *aci_login
      tenant: '{{ tenant }}'
      contract: '{{ contract }}'
      scope: tenant
      state: absent
    delegate_to: localhost

  - name: Remove Contract Subject
    aci_contract_subject:
      <<: *aci_login
      tenant: '{{ tenant }}'
      contract: '{{ contract }}'
      contract_subject: '{{ contract_subject }}'
      reverse_filter: yes
      state: absent
    delegate_to: localhost

  - name: Bind Contract Subject to filter
    aci_contract_subject_to_filter:
      <<: *aci_login
      tenant: '{{ tenant }}'
      contract: '{{ contract }}'
      contract_subject: '{{ contract_subject }}'
      filter: '{{ filter }}'
      state: absent
    delegate_to: localhost
